FROM node:14-alpine

RUN mkdir -p /home/query-node && chown -R node:node /home/query-node
WORKDIR /home/query-node

COPY --from=builder /home/hydra-builder/generated/graphql-server ./generated/graphql-server

COPY --from=builder /home/hydra-builder/node_modules ./node_modules
COPY --from=builder /home/hydra-builder/package.json .
COPY --from=builder /home/hydra-builder/yarn.lock .

RUN yarn --frozen-lockfile

CMD ["sh", "-c", "yarn query-node:start:prod"]
